//W3Schools
var films = [
    {
		"pageId":"y1928",
		"oscarYear":"1928", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Wings_poster.jpg/220px-Wings_poster.jpg",
		"filmName": "Wings (1927)",
		"switchId": "seenSwitch1928",
		"year":"1927",
		"director":"William A Wellman",
		"cast":"Clara Bow, Charles 'Buddy' Rogers, Richard Arlen, Gary Cooper",
		"plot":"Two young men, one rich, one middle class, who are in love with the same woman, become fighter pilots in World War I.",
		"imdbRef":"http://www.imdb.com/title/tt0018578/",
		"wikiRef":"https://en.wikipedia.org/wiki/Wings_(1927_film)",
	},
	{ 
		"pageId":"y1929",
		"oscarYear":"1929", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Broadway_Melody_poster.jpg/220px-Broadway_Melody_poster.jpg",
		"filmName": "The Broadway Melody (1929)",
		"switchId": "seenSwitch1929",
		"year":"1929",
		"director":"Harry Beaumont",
		"cast":"Charles King, Anita Page, Bessie Love,Jed Prouty",
		"plot":"A pair of sisters from the vaudeville circuit try to make it big time on Broadway, but matters of the heart complicate the attempt.",
		"imdbRef":"http://www.imdb.com/title/tt0019729/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Broadway_Melodyhttps://en.wikipedia.org/wiki/The_Broadway_Melody",
	},
	{
		"pageId":"y1930",
		"oscarYear":"1930", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/All_Quiet_on_the_Western_Front_%281930_film%29_poster.jpg/220px-All_Quiet_on_the_Western_Front_%281930_film%29_poster.jpg",
		"filmName": "All Quiet on the Western Front (1930)",
		"switchId": "seenSwitch1930",
		"year":"1930",
		"director":"Lewis Milestone",
		"cast":"Lew Ayres, Louis Wolheim",
		"plot":"A young soldier faces profound disillusionment in the soul-destroying horror of World War I.",
		"imdbRef":"http://www.imdb.com/title/tt0020629/",
		"wikiRef":"https://en.wikipedia.org/wiki/All_Quiet_on_the_Western_Front_(1930_film)",
	},
	{
		"pageId":"y1931",
		"oscarYear":"1931", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/9/9e/Cimarron_%281931_film%29_poster.jpg/225px-Cimarron_%281931_film%29_poster.jpg",
		"filmName":"Cimarron (1931)",
		"switchId":"seenSwitch1931",
		"year":"1931",
		"director":"Wesley Ruggles",
		"cast":"Richard Dix, Irene Dunne",
		"plot":"A newspaper editor settles in an Oklahoma boom town with his reluctant wife at the end of the nineteenth century.",
		"imdbRef":"http://www.imdb.com/title/tt0021746/",
		"wikiRef":"https://en.wikipedia.org/wiki/Cimarron_(1931_film)",
	},
	{
		"pageId":"y1932",
		"oscarYear":"1932", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d6/GrandHotelFilmPoster.jpg/220px-GrandHotelFilmPoster.jpg",
		"filmName":"Grand Hotel (1932)",
		"switchId":"seenSwitch1932",
		"year":"1932",
		"director":"Edmund Goulding",
		"cast":"Greta Garbo, John Barrymore, Joan Crawford, Wallace Beery, Lionel Barrymore, Lewis Stone, Jean Hersholt",
		"plot":"A group of very different individuals staying at a luxurious hotel in Berlin deal with each of their respective dramas.",
		"imdbRef":"http://www.imdb.com/title/tt0022958/",
		"wikiRef":"https://en.wikipedia.org/wiki/Grand_Hotel_(film)",
	},
	{
		"pageId":"y1933",
		"oscarYear":"1933", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/3/3f/Cavalcade_film_poster.jpg/220px-Cavalcade_film_poster.jpg",
		"filmName":"Cavalcade (1933)",
		"switchId":"seenSwitch1933",
		"year":"1933",
		"director":"Frank Lloyd",
		"cast":"Diana Wynyard, Clive Brook, Una O'Connor, Herbert Mundin",
		"plot":"A cavalcade of English life from New Year's Eve 1899 until 1933 seen through the eyes of well-to-do Londoners Jane and Robert Marryot.",
		"imdbRef":"http://www.imdb.com/title/tt0023876/",
		"wikiRef":"https://en.wikipedia.org/wiki/Cavalcade_(1933_film)",
	},
	{
		"pageId":"y1934",
		"oscarYear":"1934", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Gable_ithapponepm_poster.jpg/220px-Gable_ithapponepm_poster.jpg",
		"filmName":"It Happened One Night (1934)",
		"switchId":"seenSwitch1934",
		"year":"1934",
		"director":"Frank Capra",
		"cast":"Clark Gable, Claudette Colbert",
		"plot":"A spoiled heiress, running away from her family, is helped by a man who is actually a reporter in need of a story.",
		"imdbRef":"http://www.imdb.com/title/tt0025316/",
		"wikiRef":"https://en.wikipedia.org/wiki/It_Happened_One_Night",
	},
	{
		"pageId":"y1935", 
		"oscarYear":"1935", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/b/b8/Mutiny_on_the_Bounty_poster.jpg",
		"filmName":"Mutiny on the Bounty (1935)",
		"switchId":"seenSwitch1935",
		"year":"1935",
		"director":"Frank Lloyd",
		"cast":"Charles Laughton, Clark Gable, Franchot Tone, Movita Castaneda, Mamo Clark",
		"plot":"Fletcher Christian successfully leads a revolt against the ruthless Lieutenant Bligh on His Majesty's Armed Vessel 'Bounty'. However, Bligh returns one year later, hell bent on avenging his captors.",
		"imdbRef":"http://www.imdb.com/title/tt0026752/",
		"wikiRef":"https://en.wikipedia.org/wiki/Mutiny_on_the_Bounty_(1935_film)",
	},
	{
		"pageId":"y1936", 
		"oscarYear":"1936", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Great-Ziegfeld-1936-Poster.jpg/220px-Great-Ziegfeld-1936-Poster.jpg",
		"filmName":"The Great Ziegfeld (1936)",
		"switchId":"seenSwitch1936",
		"year":"1936",
		"director":"Robert Z. Leonard",
		"cast":"William Powell, Myrna Loy, Luise Rainer",
		"plot":"This biography follows the ups and downs of Florenz Ziegfeld, famed producer of extravagant stage revues.",
		"imdbRef":"http://www.imdb.com/title/tt0027698/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Great_Ziegfeld",
	},
	{
		"pageId":"y1937", 
		"oscarYear":"1937", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/6/62/The_Life_of_Emile_Zola_poster.jpg",
		"filmName":"The Life of Emile Zola (1937)",
		"switchId":"seenSwitch1937",
		"year":"1937",
		"director":"William Dieterle",
		"cast":"Paul Muni, Gloria Holden, Gale Sondergaard, Joseph Schildkraut",
		"plot":"The biopic of the famous French muckraking writer and his involvement in fighting the injustice of the Dreyfuss Affair.",
		"imdbRef":"http://www.imdb.com/title/tt0029146/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Life_of_Emile_Zola",
	},
	{
		"pageId":"y1938", 
		"oscarYear":"1938", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/7/70/You_Can%27t_Take_It_with_You_1938_Poster.jpg/220px-You_Can%27t_Take_It_with_You_1938_Poster.jpg",
		"filmName":"You Can't Take It with You (1938)",
		"switchId":"seenSwitch1938",
		"year":"1938",
		"director":"Frank Capra",
		"cast":"Jean Arthur, Lionel Barrymore, James Stewart, Edward Arnold",
		"plot":"A man from a family of rich snobs becomes engaged to a woman from a good-natured but decidedly eccentric family.",
		"imdbRef":"http://www.imdb.com/title/tt0030993/",
		"wikiRef":"https://en.wikipedia.org/wiki/You_Can%27t_Take_It_With_You_(film)",
	},
	{
		"pageId":"y1939", 
		"oscarYear":"1939", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Poster_-_Gone_With_the_Wind_01.jpg/220px-Poster_-_Gone_With_the_Wind_01.jpg",
		"filmName":"Gone with the Wind (1939)",
		"switchId":"seenSwitch1939",
		"year":"1939",
		"director":"Victor Fleming",
		"cast":"Clark Gable, Vivien Leigh, Leslie Howard, Olivia de Havilland",
		"plot":"A manipulative Southern belle carries on a turbulent affair with a blockade runner during the American Civil War.",
		"imdbRef":"http://www.imdb.com/title/tt0031381/",
		"wikiRef":"https://en.wikipedia.org/wiki/Gone_with_the_Wind_(film)",
	},
	{
		"pageId":"y1940", 
		"oscarYear":"1940", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Rebecca_1940_film_poster.jpg/220px-Rebecca_1940_film_poster.jpg",
		"filmName":"Rebecca (1940)",
		"switchId":"seenSwitch1940",
		"year":"1940",
		"director":"Alfred Hitchcock",
		"cast":"Laurence Olivier, Joan Fontaine",
		"plot":"A self-conscious bride is tormented by the memory of her husband's dead first wife.",
		"imdbRef":"http://www.imdb.com/title/tt0032976/",
		"wikiRef":"https://en.wikipedia.org/wiki/Rebecca_(1940_film)",
	},
	{
		"pageId":"y1941", 
		"oscarYear":"1941", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/0/00/How_Green_Was_My_Valley_poster.jpg/220px-How_Green_Was_My_Valley_poster.jpg",
		"filmName":"How Green Was My Valley (1941)",
		"switchId":"seenSwitch1941",
		"year":"1941",
		"director":"John Ford",
		"cast":"Walter Pidgeon, Maureen O'Hara, Anna Lee, Donald Crisp, Roddy McDowall",
		"plot":"At the turn of the century in a Welsh mining village, the Morgans, he stern, she gentle, raise coal-mining sons and hope their youngest will find a better life.",
		"imdbRef":"http://www.imdb.com/title/tt0033729/",
		"wikiRef":"https://en.wikipedia.org/wiki/How_Green_Was_My_Valley_(film)",
	},
	{
		"pageId":"y1942", 
		"oscarYear":"1942", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Mrs_Miniver_poster.gif/220px-Mrs_Miniver_poster.gif",
		"filmName":"Mrs. Miniver (1942)",
		"switchId":"seenSwitch1942",
		"year":"1942",
		"director":"William Wyler",
		"cast":"Greer Garson, Walter Pidgeon",
		"plot":"A British family struggles to survive the first months of World War II.",
		"imdbRef":"http://www.imdb.com/title/tt0035093/",
		"wikiRef":"https://en.wikipedia.org/wiki/Mrs._Miniver_(film)",
	},
	{
		"pageId":"y1943", 
		"oscarYear":"1943", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/CasablancaPoster-Gold.jpg/220px-CasablancaPoster-Gold.jpg",
		"filmName":"Casablanca (1942)",
		"switchId":"seenSwitch1943",
		"year":"1942",
		"director":"Michael Curtiz",
		"cast":"Humphrey Bogart, Ingrid Bergman, Paul Henreid",
		"plot":"In Casablanca, Morocco during the early days of World War II, an American expatriate meets a former lover, with unforeseen complications.",
		"imdbRef":"http://www.imdb.com/title/tt0034583/",
		"wikiRef":"https://en.wikipedia.org/wiki/Casablanca_(film)",
	},
	{
		"pageId":"y1944", 
		"oscarYear":"1944", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/a/ad/GoingmywayBing.jpg/220px-GoingmywayBing.jpg",
		"filmName":"Going My Way (1944)",
		"switchId":"seenSwitch1944",
		"year":"1944",
		"director":"Leo McCarey",
		"cast":"Bing Crosby, Barry Fitzgerald, Risë Stevens",
		"plot":"After joining a parish, youthful Father Chuck O'Malley's worldly knowledge helps him connect with a gang of kids looking for direction, winning over his aging, conventional superior, Father Fitzgibbon.",
		"imdbRef":"http://www.imdb.com/title/tt0036872/",
		"wikiRef":"https://en.wikipedia.org/wiki/Going_My_Way",
	},
	{
		"pageId":"y1945", 
		"oscarYear":"1945", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/59/The_Lost_Weekend_poster.jpg/220px-The_Lost_Weekend_poster.jpg",
		"filmName":"The Lost Weekend (1945)",
		"switchId":"seenSwitch1945",
		"year":"1945",
		"director":"Billy Wilder",
		"cast":"Ray Milland, Jane Wyman",
		"plot":"The desperate life of a chronic alcoholic is followed through a four day drinking bout.",
		"imdbRef":"http://www.imdb.com/title/tt0037884/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Lost_Weekend_(film)",
	},
	{
		"pageId":"y1946", 
		"oscarYear":"1946", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/4/42/The_Best_Years_of_Our_Lives_film_poster.jpg/220px-The_Best_Years_of_Our_Lives_film_poster.jpg",
		"filmName":"The Best Years of Our Lives (1946)",
		"switchId":"seenSwitch1946",
		"year":"1946",
		"director":"William Wyler",
		"cast":"Myrna Loy, Fredric March, Dana Andrews, Teresa Wright, Virginia Mayo, Harold Russell",
		"plot":"Three World War II veterans return home to small-town America to discover that they and their families have been irreparably changed.",
		"imdbRef":"http://www.imdb.com/title/tt0036868/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Best_Years_of_Our_Lives",
	},
	{
		"pageId":"y1947", 
		"oscarYear":"1947", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Gentleman%27s_Agreement_%281947_movie_poster%29.jpg/220px-Gentleman%27s_Agreement_%281947_movie_poster%29.jpg",
		"filmName":"Gentleman's Agreement (1947)",
		"switchId":"seenSwitch1947",
		"year":"1947",
		"director":"Elia Kazan",
		"cast":"Gregory Peck, Dorothy McGuire, John Garfield, Celeste Holm, June Havoc, Anne Revere",
		"plot":"A reporter pretends to be Jewish in order to cover a story on anti-Semitism, and personally discovers the true depths of bigotry and hatred.",
		"imdbRef":"http://www.imdb.com/title/tt0039416/",
		"wikiRef":"https://en.wikipedia.org/wiki/Gentleman%27s_Agreement",
	},
	{
		"pageId":"y1948", 
		"oscarYear":"1948", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Amleto48-01.jpg/220px-Amleto48-01.jpg",
		"filmName":"Hamlet (1948)",
		"switchId":"seenSwitch1948",
		"year":"1948",
		"director":"Laurence Olivier",
		"cast":"Laurence Olivier",
		"plot":"Prince Hamlet struggles over whether or not he should kill his uncle, whom he suspects has murdered his father, the former king.",
		"imdbRef":"http://www.imdb.com/title/tt0040416/",
		"wikiRef":"https://en.wikipedia.org/wiki/Hamlet_(1948_film)",
	},
	{
		"pageId":"y1949", 
		"oscarYear":"1949", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b3/All_the_King%27s_Men_%281949_movie_poster%29.jpg/220px-All_the_King%27s_Men_%281949_movie_poster%29.jpg",
		"filmName":"All the King's Men (1949)",
		"switchId":"seenSwitch1949",
		"year":"1949",
		"director":"Robert Rossen",
		"cast":"Broderick Crawford, John Ireland, Mercedes McCambridge, Joanne Dru, John Derek",
		"plot":"The rise and fall of a corrupt politician, who makes his friends richer and retains power by dint of a populist appeal.",
		"imdbRef":"http://www.imdb.com/title/tt0041113/",
		"wikiRef":"https://en.wikipedia.org/wiki/All_the_King%27s_Men_(1949_film)",
	},
	{
		"pageId":"y1950", 
		"oscarYear":"1950", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/2/22/AllAboutEve.jpeg/220px-AllAboutEve.jpeg",
		"filmName":"All About Eve (1950)",
		"switchId":"seenSwitch1950",
		"year":"1950",
		"director":"Joseph L. Mankiewicz",
		"cast":"Bette Davis, Anne Baxter, George Sanders, Celeste Holm",
		"plot":"An ingenue insinuates herself in to the company of an established but aging stage actress and her circle of theater friends.",
		"imdbRef":"http://www.imdb.com/title/tt0042192/",
		"wikiRef":"https://en.wikipedia.org/wiki/All_About_Eve",
	},
	{
		"pageId":"y1951", 
		"oscarYear":"1951", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/59/An_American_in_Paris_poster.jpg/215px-An_American_in_Paris_poster.jpg",
		"filmName":"An American in Paris (1951)",
		"switchId":"seenSwitch1951",
		"year":"1951",
		"director":"Vincente Minnelli",
		"cast":"Gene Kelly, Leslie Caron, Oscar Levant, Georges Guétary, Nina Foch",
		"plot":"Three friends struggle to find work in Paris. Things become more complicated when two of them fall in love with the same woman.",
		"imdbRef":"http://www.imdb.com/title/tt0043278/",
		"wikiRef":"https://en.wikipedia.org/wiki/An_American_in_Paris_(film)",
	},
	{
		"pageId":"y1952", 
		"oscarYear":"1952", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/9/93/Greatest.gif/220px-Greatest.gif",
		"filmName":"The Greatest Show on Earth (1952)",
		"switchId":"seenSwitch1952",
		"year":"1952",
		"director":"Cecil B. DeMille",
		"cast":"Betty Hutton, Cornel Wilde, Charlton Heston, James Stewart, Dorothy Lamour, Gloria Grahame, Lyle Bettger",
		"plot":"The dramatic lives of trapeze artists, a clown, and an elephant trainer are told against a background of circus spectacle.",
		"imdbRef":"http://www.imdb.com/title/tt0044672/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Greatest_Show_on_Earth",
	},
	{
		"pageId":"y1953", 
		"oscarYear":"1953", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/c/ce/From_Here_to_Eternity_film_poster.jpg/220px-From_Here_to_Eternity_film_poster.jpg",
		"filmName":"From Here to Eternity (1953)",
		"switchId":"seenSwitch1953",
		"year":"1953",
		"director":"Fred Zinnemann",
		"cast":"Burt Lancaster, Montgomery Clift, Deborah Kerr, Donna Reed, Frank Sinatra, Ernest Borgnine, Philip Ober, Jack Warden",
		"plot":"In 1941 Hawaii, a private is cruelly punished for not boxing on his unit's team, while his captain's wife and second in command are falling in love.",
		"imdbRef":"http://www.imdb.com/title/tt0045793/",
		"wikiRef":"https://en.wikipedia.org/wiki/From_Here_to_Eternity",
	},
	{
		"pageId":"y1954", 
		"oscarYear":"1954", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/f/f4/On_the_Waterfront_poster.jpg/220px-On_the_Waterfront_poster.jpg",
		"filmName":"On the Waterfront (1954)",
		"switchId":"seenSwitch1954",
		"year":"1954",
		"director":"Elia Kazan",
		"cast":"Marlon Brando",
		"plot":"An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.",
		"imdbRef":"http://www.imdb.com/title/tt0047296/",
		"wikiRef":"https://en.wikipedia.org/wiki/On_the_Waterfront",
	},
	{
		"pageId":"y1955", 
		"oscarYear":"1955", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/f/f6/Marty_film_poster.jpg/220px-Marty_film_poster.jpg",
		"filmName":"Marty (1955)",
		"switchId":"seenSwitch1955",
		"year":"1955",
		"director":"Delbert Mann",
		"cast":"Ernest Borgnine, Betsy Blair, Joe Mantell, Frank Sutton, Karen Steele, Jerry Paris, Esther Minciotti, Augusta Ciolli",
		"plot":"A middle-aged butcher and a school teacher who have given up on the idea of love meet at a dance and fall for each other.",
		"imdbRef":"http://www.imdb.com/title/tt0048356/",
		"wikiRef":"https://en.wikipedia.org/wiki/Marty_(film)",
	},
	{
		"pageId":"y1956", 
		"oscarYear":"1956", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/5e/Around_the_World_in_80_Days_%281956_film%29_poster.jpg/220px-Around_the_World_in_80_Days_%281956_film%29_poster.jpg",
		"filmName":"Around the World in 80 Days (1956)",
		"switchId":"seenSwitch1956",
		"year":"1956",
		"director":"Michael Anderson",
		"cast":"Cantinflas, David Niven, Robert Newton, Shirley MacLaine",
		"plot":"A Victorian Englishman bets that with the new steamships and railways he can navigate the world in 80 days.",
		"imdbRef":"http://www.imdb.com/title/tt0048960/",
		"wikiRef":"https://en.wikipedia.org/wiki/Around_the_World_in_80_Days_(1956_film)",
	},
	{
		"pageId":"y1957", 
		"oscarYear":"1957", 
		"poster":"https://www.movieposter.com/posters/archive/main/86/MPW-43042",
		"filmName":"The Bridge on the River Kwai (1957)",
		"switchId":"seenSwitch1957",
		"year":"1957",
		"director":"David Lean<",
		"cast":"William Holden, Alec Guinness, Jack Hawkins",
		"plot":"After settling his differences with a Japanese PoW camp commander, a British colonel co-operates to oversee his men's construction of a railway bridge for their captors - while oblivious to a plan by the Allies to destroy it.",
		"imdbRef":"http://www.imdb.com/title/tt0050212/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Bridge_on_the_River_Kwai",
	},
	{
		"pageId":"y1958", 
		"oscarYear":"1958", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/db/AmericanGigiPoster.jpg/215px-AmericanGigiPoster.jpg",
		"filmName":"Gigi (1958)",
		"switchId":"seenSwitch1958",
		"year":"1958",
		"director":"Vincente Minnelli",
		"cast":"Leslie Caron, Louis Jourdan, Maurice Chevalier, Hermione Gingold",
		"plot":"Weary of the conventions of Parisian society, a rich playboy and a youthful courtesan-in-training enjoy a platonic friendship, but it may not stay platonic for long.",
		"imdbRef":"http://www.imdb.com/title/tt0051658/",
		"wikiRef":"https://en.wikipedia.org/wiki/Gigi_(1958_film)",
	},
	{
		"pageId":"y1959", 
		"oscarYear":"1959", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Ben_hur_1959_poster.jpg/220px-Ben_hur_1959_poster.jpg",
		"filmName":"Ben-Hur (1959)",
		"switchId":"seenSwitch1959",
		"year":"1959",
		"director":"William Wyler",
		"cast":"Charlton Heston, Jack Hawkins, Haya Harareet, Stephen Boyd, Hugh Griffith",
		"plot":"When a Jewish prince is betrayed and sent into slavery by a Roman friend, he regains his freedom and comes back for revenge.",
		"imdbRef":"http://www.imdb.com/title/tt0052618/",
		"wikiRef":"https://en.wikipedia.org/wiki/Ben-Hur_(1959_film)",
	},
	{
		"pageId":"y1960", 
		"oscarYear":"1960", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/bb/Apartment_60.jpg/220px-Apartment_60.jpg",
		"filmName":"The Apartment (1960)",
		"switchId":"seenSwitch1960",
		"year":"1960",
		"director":"Billy Wilder",
		"cast":"Jack Lemmon, Shirley MacLaine, Fred MacMurray, Jack Kruschen",
		"plot":"A man tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.",
		"imdbRef":"http://www.imdb.com/title/tt0053604/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Apartment",
	},
	{
		"pageId":"y1961", 
		"oscarYear":"1961", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/West_Side_Story_poster.jpg/220px-West_Side_Story_poster.jpg",
		"filmName":"West Side Story (1961)",
		"switchId":"seenSwitch1961",
		"year":"1961",
		"director":"Jerome Robbins, Robert Wise",
		"cast":"Natalie Wood, Richard Beymer, Rita Moreno, George Chakiris, Russ Tamblyn",
		"plot":"Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.",
		"imdbRef":"http://www.imdb.com/title/tt0055614/",
		"wikiRef":"https://en.wikipedia.org/wiki/West_Side_Story_(film)",
	},
	{
		"pageId":"y1962", 
		"oscarYear":"1962", 
		"poster":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Lawrence_of_arabia_ver3_xxlg.jpg/220px-Lawrence_of_arabia_ver3_xxlg.jpg",
		"filmName":"Lawrence of Arabia (1962)",
		"switchId":"seenSwitch1962",
		"year":"1962",
		"director":"David Lean",
		"cast":"Alec Guinness, Anthony Quinn, Jack Hawkins, José Ferrer, Anthony Quayle, Claude Rains, Arthur Kennedy, Omar Sharif, Peter O'Toole",
		"plot":"The story of TE Lawrence, the English officer who successfully united and lead the diverse, often warring, Arab tribes during World War I in order to fight the Turks.",
		"imdbRef":"http://www.imdb.com/title/tt0056172/",
		"wikiRef":"https://en.wikipedia.org/wiki/Lawrence_of_Arabia_(film)",
	},
	{
		"pageId":"y1963", 
		"oscarYear":"1963", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/c/ca/Poster_-_Tom_Jones_01.jpg/220px-Poster_-_Tom_Jones_01.jpg",
		"filmName":"Tom Jones (1963)",
		"switchId":"seenSwitch1963",
		"year":"1963",
		"director":"Tony Richardson",
		"cast":"Albert Finney, Susannah York, Hugh Griffith, Edith Evans, Diane Cilento, Joyce Redman",
		"plot":"In this adaptation of Henry Fielding's novel, a country boy in 18th-century England becomes a playboy.",
		"imdbRef":"http://www.imdb.com/title/tt0057590/",
		"wikiRef":"https://en.wikipedia.org/wiki/Tom_Jones_(1963_film)",
	},
	{
		"pageId":"y1964", 
		"oscarYear":"1964", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/My_fair_lady_poster.jpg/220px-My_fair_lady_poster.jpg",
		"filmName":"My Fair Lady (1964)",
		"switchId":"seenSwitch1964",
		"year":"1964",
		"director":"George Cukor",
		"cast":"Audrey Hepburn, Rex Harrison, Stanley Holloway, Wilfrid Hyde-White, Gladys Cooper, Jeremy Brett",
		"plot":"A misogynistic and snobbish phonetics professor agrees to a wager that he can take a flower girl and make her presentable in high society.",
		"imdbRef":"http://www.imdb.com/title/tt0058385/",
		"wikiRef":"https://en.wikipedia.org/wiki/My_Fair_Lady_(film)",
	},
	{
		"pageId":"y1965", 
		"oscarYear":"1965", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/c/c6/Sound_of_music.jpg/220px-Sound_of_music.jpg",
		"filmName":"The Sound of Music (1965)",
		"switchId":"seenSwitch1965",
		"year":"1965",
		"director":"Robert Wise",
		"cast":"Julie Andrews, Christopher Plummer",
		"plot":"A woman leaves an Austrian convent to become a governess to the children of a Naval officer widower.",
		"imdbRef":"http://www.imdb.com/title/tt0059742/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Sound_of_Music_(film)",
	},
	{
		"pageId":"y1966", 
		"oscarYear":"1966", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/c/cb/A_Man_for_All_Seasons_%281966_movie_poster%29.gif/220px-A_Man_for_All_Seasons_%281966_movie_poster%29.gif",
		"filmName":"A Man for All Seasons (1966)",
		"switchId":"seenSwitch1966",
		"year":"1966",
		"director":"Fred Zinnemann",
		"cast":"Paul Scofield, Wendy Hiller, Leo McKern, Orson Welles, Robert Shaw, Susannah York",
		"plot":"The story of Thomas More, who stood up to King Henry VIII when the King rejected the Roman Catholic Church to obtain a divorce and remarriage.",
		"imdbRef":"http://www.imdb.com/title/tt0060665/",
		"wikiRef":"https://en.wikipedia.org/wiki/A_Man_for_All_Seasons_(1966_film)",
	},
	{
		"pageId":"y1967", 
		"oscarYear":"1967", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d5/In_the_Heat_of_the_Night_%28film%29.jpg/220px-In_the_Heat_of_the_Night_%28film%29.jpg",
		"filmName":"In the Heat of the Night (1967)",
		"switchId":"seenSwitch1967",
		"year":"1967",
		"director":"Norman Jewison",
		"cast":"Sidney Poitier, Rod Steiger, Warren Oates, Lee Grant",
		"plot":"An African American police detective is asked to investigate a murder in a racially hostile southern town.",
		"imdbRef":"http://www.imdb.com/title/tt0061811/",
		"wikiRef":"https://en.wikipedia.org/wiki/In_the_Heat_of_the_Night_(film)",
	},
	{
		"pageId":"y1968", 
		"oscarYear":"1968", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d9/Oliver%21_%281968_movie_poster%29.jpg/220px-Oliver%21_%281968_movie_poster%29.jpg",
		"filmName":"Oliver! (1968)",
		"switchId":"seenSwitch1968",
		"year":"1968",
		"director":"Carol Reed",
		"cast":"Ron Moody, Oliver Reed, Harry Secombe, Shani Wallis, Mark Lester, Jack Wild",
		"plot":"Musical adaptation about an orphan who runs away from an orphanage and hooks up with a group of boys trained to be pickpockets by an elderly mentor.",
		"imdbRef":"http://www.imdb.com/title/tt0063385/",
		"wikiRef":"https://en.wikipedia.org/wiki/Oliver!_(film)",
	},
	{
		"pageId":"y1969", 
		"oscarYear":"1969", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/87/Midnight_Cowboy.jpg/220px-Midnight_Cowboy.jpg",
		"filmName":"Midnight Cowboy (1969)",
		"switchId":"seenSwitch1969",
		"year":"1969",
		"director":"John Schlesinger",
		"cast":"Dustin Hoffman, Jon Voight, Sylvia Miles, Brenda Vaccaro",
		"plot":"A naive hustler goes to New York to seek personal fortune but in the process finds himself a new friend.",
		"imdbRef":"http://www.imdb.com/title/tt0064665/",
		"wikiRef":"https://en.wikipedia.org/wiki/Midnight_Cowboy",
	},
	{
		"pageId":"y1970", 
		"oscarYear":"1970", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/70_patton.jpg/220px-70_patton.jpg",
		"filmName":"Patton (1970)",
		"switchId":"seenSwitch1970",
		"year":"1970",
		"director":"Franklin J. Schaffner",
		"cast":"George C. Scott, Karl Malden, Michael Bates, Karl Michael Vogler",
		"plot":"The World War II phase of the career of the controversial American general, George S. Patton.",
		"imdbRef":"http://www.imdb.com/title/tt0066206/",
		"wikiRef":"https://en.wikipedia.org/wiki/Patton_(film)",
	},
	{
		"pageId":"y1971", 
		"oscarYear":"1971", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/TheFrenchConnection.jpg/220px-TheFrenchConnection.jpg",
		"filmName":"The French Connection (1971)",
		"switchId":"seenSwitch1971",
		"year":"1971",
		"director":"William Friedkin",
		"cast":"Gene Hackman, Fernando Rey, Roy Scheider, Tony Lo Bianco, Marcel Bozzuffi",
		"plot":"A pair of NYC cops in the Narcotics Bureau stumble onto a drug smuggling job with a French connection.",
		"imdbRef":"http://www.imdb.com/title/tt0067116/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_French_Connection_(film)",
	},
	{
		"pageId":"y1972", 
		"oscarYear":"1972", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Godfather_ver1.jpg/220px-Godfather_ver1.jpg",
		"filmName":"The Godfather (1972)",
		"switchId":"seenSwitch1972",
		"year":"1972",
		"director":"Francis Ford Coppola",
		"cast":"Marlon Brando, Al Pacino, James Caan, Richard Castellano, Robert Duvall, Sterling Hayden, John Marley, Richard Conte, Diane Keaton",
		"plot":"The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
		"imdbRef":"http://www.imdb.com/title/tt0068646/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Godfather",
	},
	{
		"pageId":"y1973", 
		"oscarYear":"1973", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/9/9c/Stingredfordnewman.jpg",
		"filmName":"The Sting (1973)",
		"switchId":"seenSwitch1973",
		"year":"1973",
		"director":"George Roy Hill",
		"cast":"Paul Newman, Robert Redford, Robert Shaw",
		"plot":"In Chicago in September 1936, a young con man seeking revenge for his murdered partner teams up with a master of the big con to win a fortune from a criminal banker.",
		"imdbRef":"http://www.imdb.com/title/tt0070735/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Sting",
	},
	{
		"pageId":"y1974", 
		"oscarYear":"1974", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/0/03/Godfather_part_ii.jpg/220px-Godfather_part_ii.jpg",
		"filmName":"The Godfather Part II (1974)",
		"switchId":"seenSwitch1974",
		"year":"1974",
		"director":"Francis Ford Coppola",
		"cast":"Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro, Talia Shire, Morgana King, John Cazale, Marianna Hill, Lee Strasberg",
		"plot":"The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.",
		"imdbRef":"http://www.imdb.com/title/tt0071562/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Godfather_Part_II",
	},
	{
		"pageId":"y1975", 
		"oscarYear":"1975", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/2/26/One_Flew_Over_the_Cuckoo%27s_Nest_poster.jpg/220px-One_Flew_Over_the_Cuckoo%27s_Nest_poster.jpg",
		"filmName":"One Flew Over the Cuckoo's Nest (1975)",
		"switchId":"seenSwitch1975",
		"year":"1975",
		"director":"Miloš Forman",
		"cast":"Jack Nicholson, Louise Fletcher",
		"plot":"A criminal pleads insanity after getting into trouble again and once in the mental institution rebels against the oppressive nurse and rallies up the scared patients.",
		"imdbRef":"http://www.imdb.com/title/tt0073486/",
		"wikiRef":"https://en.wikipedia.org/wiki/One_Flew_Over_the_Cuckoo%27s_Nest_(film)",
	},
	{
		"pageId":"y1976", 
		"oscarYear":"1976", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/1/18/Rocky_poster.jpg/220px-Rocky_poster.jpg",
		"filmName":"Rocky (1976)",
		"switchId":"seenSwitch1976",
		"year":"1976",
		"director":"John G. Avildsen",
		"cast":"Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers, Burgess Meredith",
		"plot":"Rocky Balboa, a small-time boxer, gets a supremely rare chance to fight the heavy-weight champion, Apollo Creed, in a bout in which he strives to go the distance for his self-respect.",
		"imdbRef":"http://www.imdb.com/title/tt0075148/",
		"wikiRef":"https://en.wikipedia.org/wiki/Rocky",
	},
	{
		"pageId":"y1977", 
		"oscarYear":"1977", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/Anniehallposter.jpg/220px-Anniehallposter.jpg",
		"filmName":"Annie Hall (1977)",
		"switchId":"seenSwitch1977",
		"year":"1977",
		"director":"Woody Allen",
		"cast":"Woody Allen, Diane Keaton, Tony Roberts, Carol Kane, Paul Simon, Janet Margolin, Shelley Duvall, Christopher Walken, Colleen Dewhurst",
		"plot":"Neurotic New York comedian Alvy Singer falls in love with the ditsy Annie Hall.",
		"imdbRef":"http://www.imdb.com/title/tt0075686/",
		"wikiRef":"https://en.wikipedia.org/wiki/Annie_Hall",
	},
	{
		"pageId":"y1978", 
		"oscarYear":"1978", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/57/The_Deer_Hunter_poster.jpg/220px-The_Deer_Hunter_poster.jpg",
		"filmName":"The Deer Hunter (1978)",
		"switchId":"seenSwitch1978",
		"year":"1978",
		"director":"Michael Cimino",
		"cast":"Robert De Niro, Christopher Walken, John Savage, John Cazale, Meryl Streep, George Dzundza",
		"plot":"An in-depth examination of the ways in which the U.S. Vietnam war impacts and disrupts the lives of people in a small industrial town in Pennsylvania.",
		"imdbRef":"http://www.imdb.com/title/tt0077416/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Deer_Hunter",
	},
	{
		"pageId":"y1979", 
		"oscarYear":"1979", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Oscar_posters_79.jpg/220px-Oscar_posters_79.jpg",
		"filmName":"Kramer vs. Kramer (1979)",
		"switchId":"seenSwitch1979",
		"year":"1979",
		"director":"Robert Benton",
		"cast":"Dustin Hoffman, Meryl Streep, Justin Henry, Jane Alexander",
		"plot":"Ted Kramer's wife leaves her husband, allowing for a lost bond to be rediscovered between Ted and his son, Billy. But a heated custody battle ensues over the divorced couple's son, deepening the wounds left by the separation.",
		"imdbRef":"http://www.imdb.com/title/tt0079417/",
		"wikiRef":"https://en.wikipedia.org/wiki/Kramer_vs._Kramer",
	},
	{
		"pageId":"y1980", 
		"oscarYear":"1980", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/88/OrdinaryPeople.jpg/220px-OrdinaryPeople.jpg",
		"filmName":"Ordinary People (1980)",
		"switchId":"seenSwitch1980",
		"year":"1980",
		"director":"Robert Redford",
		"cast":"Donald Sutherland, Mary Tyler Moore, Judd Hirsch, Timothy Hutton",
		"plot":"The accidental death of the older son of an affluent family deeply strains the relationships among the bitter mother, the good-natured father, and the guilt-ridden younger son.",
		"imdbRef":"http://www.imdb.com/title/tt0081283/",
		"wikiRef":"https://en.wikipedia.org/wiki/Ordinary_People",
	},
	{
		"pageId":"y1981", 
		"oscarYear":"1981", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b5/Chariots_of_fire.jpg/220px-Chariots_of_fire.jpg",
		"filmName":"Chariots of Fire (1981)",
		"switchId":"seenSwitch1981",
		"year":"1981",
		"director":"Hugh Hudson",
		"cast":"Ben Cross, Ian Charleson, Nigel Havers, Cheryl Campbell, Alice Krige, Lindsay Anderson, Dennis Christopher, Nigel Davenport, Brad Davis, Peter Egan, Sir John Gielgud, Ian Holm, Patrick Magee",
		"plot":"Two British track athletes, one a determined Jew and the other a devout Christian, compete in the 1924 Olympics.",
		"imdbRef":"http://www.imdb.com/title/tt0082158/",
		"wikiRef":"https://en.wikipedia.org/wiki/Chariots_of_Fire",
	},
	{
		"pageId":"y1982", 
		"oscarYear":"1982", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/1/10/Gandhi-poster.png",
		"filmName":"Gandhi (1982)",
		"switchId":"seenSwitch1982",
		"year":"1982",
		"director":"Richard Attenborough",
		"cast":"Candice Bergen, Edward Fox, John Gielgud, Trevor Howard, John Mills, Martin Sheen, Ben Kingsley",
		"plot":"Gandhi's character is fully explained as a man of nonviolence. Through his patience, he is able to drive the British out of the subcontinent. And the stubborn nature of Jinnah and his commitment towards Pakistan is portrayed.",
		"imdbRef":"http://www.imdb.com/title/tt0083987/",
		"wikiRef":"https://en.wikipedia.org/wiki/Gandhi_(film)",
	},
	{
		"pageId":"y1983", 
		"oscarYear":"1983", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/Terms_of_Endearment%2C_1983_film.jpg/220px-Terms_of_Endearment%2C_1983_film.jpg",
		"filmName":"Terms of Endearment (1983)",
		"switchId":"seenSwitch1983",
		"year":"1983",
		"director":"James L. Brooks",
		"cast":"Shirley MacLaine, Debra Winger, Jack Nicholson, Danny DeVito, John Lithgow",
		"plot":"Follows hard-to-please Aurora looking for love and her daughter's family problems.",
		"imdbRef":"http://www.imdb.com/title/tt0086425/",
		"wikiRef":"https://en.wikipedia.org/wiki/Terms_of_Endearment",
	},
	{
		"pageId":"y1984", 
		"oscarYear":"1984", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/2/2f/Amadeusmov.jpg/220px-Amadeusmov.jpg",
		"filmName":"Amadeus (1984)",
		"switchId":"seenSwitch1984",
		"year":"1984",
		"director":"Miloš Forman",
		"cast":"F. Murray Abraham, Tom Hulce, Elizabeth Berridge, Simon Callow, Roy Dotrice, Christine Ebersole, Jeffrey Jones, Charles Kay",
		"plot":"The incredible story of Wolfgang Amadeus Mozart, told by his peer and secret rival Antonio Salieri - now confined to an insane asylum.",
		"imdbRef":"http://www.imdb.com/title/tt0086879/",
		"wikiRef":"https://en.wikipedia.org/wiki/Amadeus_(film)",
	},
	{
		"pageId":"y1985", 
		"oscarYear":"1985", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/3/3c/Out_of_africa_poster.jpg/220px-Out_of_africa_poster.jpg",
		"filmName":"Out of Africa (1985)",
		"switchId":"seenSwitch1985",
		"year":"1985",
		"director":"Sydney Pollack",
		"cast":"Robert Redford, Meryl Streep, Klaus Maria Brandauer",
		"plot":"In 20th-century colonial Kenya, a Danish baroness/plantation owner has a passionate love affair with a free-spirited big-game hunter.",
		"imdbRef":"http://www.imdb.com/title/tt0089755/",
		"wikiRef":"https://en.wikipedia.org/wiki/Out_of_Africa_(film)",
	},
	{
		"pageId":"y1986", 
		"oscarYear":"1986", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a9/Platoon_posters_86.jpg/220px-Platoon_posters_86.jpg",
		"filmName":"Platoon (1986)",
		"switchId":"seenSwitch1986",
		"year":"1986",
		"director":"Oliver Stone",
		"cast":"Tom Berenger, Willem Dafoe, Charlie Sheen",
		"plot":"A young recruit in Vietnam faces a moral crisis when confronted with the horrors of war and the duality of man.",
		"imdbRef":"http://www.imdb.com/title/tt0091763/",
		"wikiRef":"https://en.wikipedia.org/wiki/Platoon_(film)",
	},
	{
		"pageId":"y1987", 
		"oscarYear":"1987", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/The_Last_Emperor_filmposter.jpg/220px-The_Last_Emperor_filmposter.jpg",
		"filmName":"The Last Emperor (1987)",
		"switchId":"seenSwitch1987",
		"year":"1987",
		"director":"Bernardo Bertolucci",
		"cast":"John Lone, Joan Chen, Peter O'Toole, Ying Ruocheng, Victor Wong, Dennis Dun, Ryuichi Sakamoto",
		"plot":"The story of the final Emperor of China.",
		"imdbRef":"http://www.imdb.com/title/tt0093389/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Last_Emperor",
	},
	{
		"pageId":"y1988", 
		"oscarYear":"1988", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Rain_Man_poster.jpg/220px-Rain_Man_poster.jpg",
		"filmName":"Rain Man (1988)",
		"switchId":"seenSwitch1988",
		"year":"1988",
		"director":"Barry Levinson",
		"cast":"Dustin Hoffman, Tom Cruise, Valeria Golino",
		"plot":"Selfish yuppie Charlie Babbitt's father left a fortune to his savant brother Raymond and a pittance to Charlie; they travel cross-country.",
		"imdbRef":"http://www.imdb.com/title/tt0095953/",
		"wikiRef":"https://en.wikipedia.org/wiki/Rain_Man",
	},
	{
		"pageId":"y1989", 
		"oscarYear":"1989", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a5/Driving_Miss_Daisy_.jpg/220px-Driving_Miss_Daisy_.jpg",
		"filmName":"Driving Miss Daisy (1989)",
		"switchId":"seenSwitch1989",
		"year":"1989",
		"director":"Bruce Beresford",
		"cast":"Morgan Freeman, Jessica Tandy, Dan Aykroyd, Patti Lupone, Esther Rolle",
		"plot":"An old Jewish woman and her African-American chauffeur in the American South have a relationship that grows and improves over the years.",
		"imdbRef":"http://www.imdb.com/title/tt0097239/",
		"wikiRef":"https://en.wikipedia.org/wiki/Driving_Miss_Daisy",
	},
	{
		"pageId":"y1990", 
		"oscarYear":"1990", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/82/Dances_with_Wolves_poster.jpg/220px-Dances_with_Wolves_poster.jpg",
		"filmName":"Dances with Wolves (1990)",
		"switchId":"seenSwitch1990",
		"year":"1990",
		"director":"Kevin Costner",
		"cast":"Kevin Costner, Mary McDonnell, Graham Greene, Rodney A. Grant",
		"plot":"Lt. John Dunbar, exiled to a remote western Civil War outpost, befriends wolves and Indians, making him an intolerable aberration in the military.",
		"imdbRef":"http://www.imdb.com/title/tt0099348/",
		"wikiRef":"https://en.wikipedia.org/wiki/Dances_with_Wolves",
	},
	{
		"pageId":"y1991", 
		"oscarYear":"1991", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/86/The_Silence_of_the_Lambs_poster.jpg/220px-The_Silence_of_the_Lambs_poster.jpg",
		"filmName":"The Silence of the Lambs (1991)",
		"switchId":"seenSwitch1991",
		"year":"991",
		"director":"Jonathan Demme",
		"cast":"Jodie Foster, Anthony Hopkins, Scott Glenn, Ted Levine, Anthony Heald",
		"plot":"A young F.B.I. cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer who skins his victims.",
		"imdbRef":"http://www.imdb.com/title/tt0102926/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Silence_of_the_Lambs_(film)",
	},
	{
		"pageId":"y1992", 
		"oscarYear":"1992", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/4/4e/Unforgiven_2.jpg/220px-Unforgiven_2.jpg",
		"filmName":"Unforgiven (1992)",
		"switchId":"seenSwitch1992",
		"year":"1992",
		"director":"Clint Eastwood",
		"cast":"Clint Eastwood, Gene Hackman, Morgan Freeman, Richard Harris",
		"plot":"Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner and a young man.",
		"imdbRef":"http://www.imdb.com/title/tt0105695/",
		"wikiRef":"https://en.wikipedia.org/wiki/Unforgiven",
	},
	{
		"pageId":"y1993", 
		"oscarYear":"1993", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/3/38/Schindler%27s_List_movie.jpg/220px-Schindler%27s_List_movie.jpg",
		"filmName":"Schindler's List (1993)",
		"switchId":"seenSwitch1993",
		"year":"1993",
		"director":"Steven Spielberg",
		"cast":"Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall, Jonathan Sagall, Embeth Davidtz",
		"plot":"In Poland during World War II, Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
		"imdbRef":"http://www.imdb.com/title/tt0108052/",
		"wikiRef":"https://en.wikipedia.org/wiki/Schindler%27s_List",
	},
	{
		"pageId":"y1994", 
		"oscarYear":"1994", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/6/67/Forrest_Gump_poster.jpg/220px-Forrest_Gump_poster.jpg",
		"filmName":"Forrest Gump (1994)",
		"switchId":"seenSwitch1994",
		"year":"1994",
		"director":"Robert Zemeckis",
		"cast":"Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson, Sally Field",
		"plot":"Forrest Gump, while not intelligent, has accidentally been present at many historic moments, but his true love, Jenny Curran, eludes him.",
		"imdbRef":"http://www.imdb.com/title/tt0109830/",
		"wikiRef":"https://en.wikipedia.org/wiki/Forrest_Gump",
	},
	{
		"pageId":"y1995", 
		"oscarYear":"1995", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Braveheart_imp.jpg/220px-Braveheart_imp.jpg",
		"filmName":"Braveheart (1995)",
		"switchId":"seenSwitch1995",
		"year":"1995",
		"director":"Mel Gibson",
		"cast":"Mel Gibson, Sophie Marceau, Patrick McGoohan, Catherine McCormack",
		"plot":"When his secret bride is executed for assaulting an English soldier who tried to rape her, William Wallace begins a revolt against King Edward I of England.",
		"imdbRef":"http://www.imdb.com/title/tt0112573/",
		"wikiRef":"https://en.wikipedia.org/wiki/Braveheart",
	},
	{
		"pageId":"y1996", 
		"oscarYear":"1996", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/bd/The_English_Patient_Poster.jpg/220px-The_English_Patient_Poster.jpg",
		"filmName":"The English Patient (1996)",
		"switchId":"seenSwitch1996",
		"year":"1996",
		"director":"Anthony Minghella",
		"cast":"Ralph Fiennes, Juliette Binoche, Willem Dafoe, Kristin Scott Thomas",
		"plot":"At the close of WWII, a young nurse tends to a badly-burned plane crash victim. His past is shown in flashbacks, revealing an involvement in a fateful love affair.",
		"imdbRef":"http://www.imdb.com/title/tt0116209/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_English_Patient_(film)",
	},
	{
		"pageId":"y1997", 
		"oscarYear":"1997", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Titanic_poster.jpg/220px-Titanic_poster.jpg",
		"filmName":"Titanic (1997)",
		"switchId":"seenSwitch1997",
		"year":"1997",
		"director":"James Cameron",
		"cast":"Leonardo DiCaprio, Kate Winslet, Billy Zane, Kathy Bates, Frances Fisher, Victor Garber, Bernard Hill, Jonathan Hyde, Danny Nucci, David Warner, Bill Paxton, Gloria Stuart",
		"plot":"A seventeen-year-old aristocrat falls in love with a kind, but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
		"imdbRef":"http://www.imdb.com/title/tt0120338/",
		"wikiRef":"https://en.wikipedia.org/wiki/Titanic_(1997_film)",
	},
	{
		"pageId":"y1998", 
		"oscarYear":"1998", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/Shakespeare_in_Love_1998_Poster.jpg/220px-Shakespeare_in_Love_1998_Poster.jpg",
		"filmName":"Shakespeare in Love (1998)",
		"switchId":"seenSwitch1998",
		"year":"1998",
		"director":"John Madden",
		"cast":"Gwyneth Paltrow, Joseph Fiennes, Geoffrey Rush, Colin Firth, Ben Affleck, Judi Dench",
		"plot":"A young Shakespeare, out of ideas and short of cash, meets his ideal woman and is inspired to write one of his most famous plays.",
		"imdbRef":"http://www.imdb.com/title/tt0138097/",
		"wikiRef":"https://en.wikipedia.org/wiki/Shakespeare_in_Love",
	},
	{
		"pageId":"y1999", 
		"oscarYear":"1999", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b6/American_Beauty_poster.jpg/220px-American_Beauty_poster.jpg",
		"filmName":"American Beauty (1999)",
		"switchId":"seenSwitch1999",
		"year":"1999",
		"director":"Sam Mendes",
		"cast":"Kevin Spacey, Annette Bening, Thora Birch, Allison Janney, Peter Gallagher, Mena Suvari, Wes Bentley, Chris Cooper",
		"plot":"A bored suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.",
		"imdbRef":"http://www.imdb.com/title/tt0169547/",
		"wikiRef":"https://en.wikipedia.org/wiki/American_Beauty_(1999_film)",
	},
	{
		"pageId":"y2000", 
		"oscarYear":"2000", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/8d/Gladiator_ver1.jpg/220px-Gladiator_ver1.jpg",
		"filmName":"Gladiator (2000)",
		"switchId":"seenSwitch2000",
		"year":"2000",
		"director":"Ridley Scott",
		"cast":"Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed, Derek Jacobi, Djimon Hounsou, Richard Harris",
		"plot":"When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.",
		"imdbRef":"http://www.imdb.com/title/tt0172495/",
		"wikiRef":"https://en.wikipedia.org/wiki/Gladiator_(2000_film)",
	},
	{
		"pageId":"y2001", 
		"oscarYear":"2001", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/b/b8/A_Beautiful_Mind_Poster.jpg/220px-A_Beautiful_Mind_Poster.jpg",
		"filmName":"A Beautiful Mind (2001)",
		"switchId":"seenSwitch2001",
		"year":"2001",
		"director":"Ron Howard",
		"cast":"Russell Crowe, Ed Harris, Jennifer Connelly, Paul Bettany, Adam Goldberg, Judd Hirsch, Josh Lucas, Anthony Rapp, Christopher Plummer",
		"plot":"After a brilliant but asocial mathematician, John Nash, accepts secret work in cryptography, his life takes a turn for the nightmarish.",
		"imdbRef":"http://www.imdb.com/title/tt0268978/",
		"wikiRef":"https://en.wikipedia.org/wiki/A_Beautiful_Mind_(film)",
	},
	{
		"pageId":"y2002", 
		"oscarYear":"2002", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/e/e0/Chicagopostercast.jpg/220px-Chicagopostercast.jpg",
		"filmName":"Chicago (2002)",
		"switchId":"seenSwitch2002",
		"year":"2002",
		"director":"Rob Marshall",
		"cast":"Renée Zellweger, Catherine Zeta-Jones, Richard Gere, Queen Latifah, John C. Reilly, Colm Feore, Lucy Liu, Dominic West, Christine Baranski",
		"plot":"Murderesses Velma Kelly and Roxie Hart find themselves on death row together and fight for the fame that will keep them from the gallows in 1920s Chicago.",
		"imdbRef":"http://www.imdb.com/title/tt0299658/",
		"wikiRef":"https://en.wikipedia.org/wiki/Chicago_(2002_film)",
	},
	{
		"pageId":"y2003", 
		"oscarYear":"2003", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/9/9d/Lord_of_the_Rings_-_The_Return_of_the_King.jpg/220px-Lord_of_the_Rings_-_The_Return_of_the_King.jpg",
		"filmName":"The Lord of the Rings: The Return of the King (2003)",
		"switchId":"seenSwitch2003",
		"year":"2003",
		"director":"Peter Jackson",
		"cast":"Elijah Wood, Ian McKellen, Liv Tyler, Viggo Mortensen, Sean Astin, Cate Blanchett, John Rhys-Davies, Bernard Hill, Billy Boyd, Dominic Monaghan, Orlando Bloom, Hugo Weaving, Miranda Otto, David Wenham, Karl Urban, John Noble, Andy Serkis, Ian Holm, Sean Bean",
		"plot":"Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
		"imdbRef":"http://www.imdb.com/title/tt0167260/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Lord_of_the_Rings:_The_Return_of_the_King",
	},
	{
		"pageId":"y2004", 
		"oscarYear":"2004", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Million_Dollar_Baby_poster.jpg/220px-Million_Dollar_Baby_poster.jpg",
		"filmName":"Million Dollar Baby (2004)",
		"switchId":"seenSwitch2004",
		"year":"2004",
		"director":"Clint Eastwood",
		"cast":"Clint Eastwood, Hilary Swank, Morgan Freeman",
		"plot":"A determined woman works with a hardened boxing trainer to become a professional.",
		"imdbRef":"http://www.imdb.com/title/tt0405159/",
		"wikiRef":"https://en.wikipedia.org/wiki/Million_Dollar_Baby",
	},
	{
		"pageId":"y2005", 
		"oscarYear":"2005", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/d/d0/Crash_ver2.jpg/220px-Crash_ver2.jpg",
		"filmName":"Crash (2004)",
		"switchId":"seenSwitch2005",
		"year":"2004",
		"director":"Paul Haggis",
		"cast":"Sandra Bullock, Don Cheadle, Matt Dillon, Jennifer Esposito, Brendan Fraser, Terrence Howard, Ludacris, Thandie Newton, Michael Peña, Ryan Phillippe, Larenz Tate",
		"plot":"Los Angeles citizens with vastly separate lives collide in interweaving stories of race, loss and redemption.",
		"imdbRef":"http://www.imdb.com/title/tt0375679/",
		"wikiRef":"https://en.wikipedia.org/wiki/Crash_(2004_film)",
	},
	{
		"pageId":"y2006", 
		"oscarYear":"2006", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Departed234.jpg/220px-Departed234.jpg",
		"filmName":"The Departed (2006)",
		"switchId":"seenSwitch2006",
		"year":"2006",
		"director":"Martin Scorsese",
		"cast":"Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg, Martin Sheen, Ray Winstone, Vera Farmiga, Alec Baldwin",
		"plot":"An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
		"imdbRef":"http://www.imdb.com/title/tt0407887/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Departed",
	},
	{
		"pageId":"y2007", 
		"oscarYear":"2007", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/8/8b/No_Country_for_Old_Men_poster.jpg/220px-No_Country_for_Old_Men_poster.jpg",
		"filmName":"No Country for Old Men (2007)",
		"switchId":"seenSwitch2007",
		"year":"2007",
		"director":"Joel Coen, Ethan Coen",
		"cast":"Tommy Lee Jones, Javier Bardem, Josh Brolin",
		"plot":"Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.",
		"imdbRef":"http://www.imdb.com/title/tt0477348/",
		"wikiRef":"https://en.wikipedia.org/wiki/No_Country_for_Old_Men_(film)",
	},
	{
		"pageId":"y2008", 
		"oscarYear":"2008", 
		"poster":"https://www.movieposter.com/posters/archive/main/110/MPW-55462",
		"filmName":"Slumdog Millionaire (2008)",
		"switchId":"seenSwitch2008",
		"year":"2008",
		"director":"Danny Boyle",
		"cast":"Dev Patel, Freida Pinto, Madhur Mittal, Anil Kapoor, Irrfan Khan",
		"plot":"A Mumbai teen reflects on his upbringing in the slums when he is accused of cheating on the Indian Version of 'Who Wants to be a Millionaire?'",
		"imdbRef":"http://www.imdb.com/title/tt1010048/",
		"wikiRef":"https://en.wikipedia.org/wiki/Slumdog_Millionaire",
	},
	{
		"pageId":"y2009", 
		"oscarYear":"2009", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/HLposterUSA2.jpg/220px-HLposterUSA2.jpg",
		"filmName":"The Hurt Locker (2008)",
		"switchId":"seenSwitch2009",
		"year":"2008",
		"director":"Kathryn Bigelow",
		"cast":"Jeremy Renner, Anthony Mackie, Brian Geraghty, Christian Camargo, Evangeline Lilly, Ralph Fiennes, David Morse, Guy Pearce",
		"plot":"During the Iraq War, a Sergeant recently assigned to an army bomb squad is put at odds with his squad mates due to his maverick way of handling his work.",
		"imdbRef":"http://www.imdb.com/title/tt0887912/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Hurt_Locker",
	},
	{
		"pageId":"y2010", 
		"oscarYear":"2010", 
		"poster":"http://images.moviepostershop.com/the-kings-speech-movie-poster-2010-1010687836.jpg",
		"filmName":"The King's Speech (2010)",
		"switchId":"seenSwitch2010",
		"year":"2010",
		"director":"Tom Hooper",
		"cast":"Colin Firth, Geoffrey Rush, Helena Bonham Carter, Guy Pearce, Timothy Spall, Derek Jacobi, Jennifer Ehle, Michael Gambon",
		"plot":"The story of King George VI of the United Kingdom, his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it.",
		"imdbRef":"http://www.imdb.com/title/tt1504320/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_King%27s_Speech",
	},
	{
		"pageId":"y2011", 
		"oscarYear":"2011", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/The_Artist_Poster.jpg/220px-The_Artist_Poster.jpg",
		"filmName":"The Artist (2011)",
		"switchId":"seenSwitch2011",
		"year":"2011",
		"director":"Michel Hazanavicius",
		"cast":"Jean Dujardin, Bérénice Bejo",
		"plot":"A silent movie star meets a young dancer, but the arrival of talking pictures sends their careers in opposite directions.",
		"imdbRef":"http://www.imdb.com/title/tt1655442/",
		"wikiRef":"https://en.wikipedia.org/wiki/The_Artist_(film)",
	},
	{
		"pageId":"y2012", 
		"oscarYear":"2012", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Argo2012Poster.jpg/220px-Argo2012Poster.jpg",
		"filmName":"Argo (2012)",
		"switchId":"seenSwitch2012",
		"year":"2012",
		"director":"Ben Affleck",
		"cast":"Ben Affleck, Bryan Cranston, Alan Arkin, John Goodman",
		"plot":"Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1980.",
		"imdbRef":"http://www.imdb.com/title/tt1024648/",
		"wikiRef":"https://en.wikipedia.org/wiki/Argo_(2012_film)",
	},
	{
		"pageId":"y2013", 
		"oscarYear":"2013", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/5/5c/12_Years_a_Slave_film_poster.jpg/220px-12_Years_a_Slave_film_poster.jpg",
		"filmName":"12 Years a Slave (2013)",
		"switchId":"seenSwitch2013",
		"year":"2013",
		"director":"Steve McQueen",
		"cast":"Chiwetel Ejiofor, Michael Fassbender, Benedict Cumberbatch, Paul Dano, Paul Giamatti, Lupita Nyong'o, Sarah Paulson, Brad Pitt, Alfre Woodard",
		"plot":"In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.",
		"imdbRef":"http://www.imdb.com/title/tt2024544/",
		"wikiRef":"https://en.wikipedia.org/wiki/12_Years_a_Slave_(film)",
	},
	{
		"pageId":"y2014", 
		"oscarYear":"2014", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a3/Birdman_poster.jpg/220px-Birdman_poster.jpg",
		"filmName":"Birdman or (The Unexpected Virtue of Ignorance) (2014)",
		"switchId":"seenSwitch2014",
		"year":"2014",
		"director":"Alejandro G. Iñárritu",
		"cast":"Michael Keaton, Zach Galifianakis, Edward Norton, Andrea Riseborough, Amy Ryan, Emma Stone, Naomi Watts",
		"plot":"Illustrated upon the progress of his latest Broadway play, a former popular actor's struggle to cope with his current life as a wasted actor is shown.",
		"imdbRef":"http://www.imdb.com/title/tt2562232/",
		"wikiRef":"https://en.wikipedia.org/wiki/Birdman_(film)",
	},
	{
		"pageId":"y2015", 
		"oscarYear":"2015", 
		"poster":"https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Spotlight_%28film%29_poster.jpg/220px-Spotlight_%28film%29_poster.jpg",
		"filmName":"Spotlight (2015)",
		"switchId":"seenSwitch2015",
		"year":"2015",
		"director":"Tom McCarthy",
		"cast":"Mark Ruffalo, Michael Keaton, Rachel McAdams, Liev Schreiber, John Slattery, Stanley Tucci",
		"plot":"The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.",
		"imdbRef":"http://www.imdb.com/title/tt1895587/",
		"wikiRef":"https://en.wikipedia.org/wiki/Spotlight_(film)",
	}
];



function jQPages(arr, i)
{
	$out = $(
					'<div data-role="page" id="'+arr[i].pageId+'">'+
					'	<div data-role="header">'+
					'		<h1 id="oscarYear">'+arr[i].oscarYear+'</h1>'+
					'	</div>'+
					'   <div data-role="main" class="ui-content">'+
					'		<img class="filmPoster" src="'+arr[i].poster+'" />'+
					'		<h2 id="filmName">'+arr[i].filmName+'</h2>'+
					'		<span class="nowrap" >'+
					'			<label for="switch">I have seen this movie</label>&nbsp'+
					'			<input class="checkSwitch" type="checkbox" data-role="flipswitch" name="switch" id="'+arr[i].switchId+'" data-off-text="No" data-on-text="Yes" data-mini="false" >'+
					'		</span>'+
					'		<table class="filmDetailTable">'+
					'			<tr>'+
					'				<th>Year</th><td id="year">'+arr[i].year+'</td>'+
					'			</tr>'+
					'			<tr>'+
					'				<th>Director</th><td id="director">'+arr[i].director+'</td>'+
					'			</tr>'+
					'			<tr>'+
					'				<th>Main Cast</th><td id="cast">'+arr[i].cast+'</td>'+
					'			</tr>'+
					'			<tr>'+
					'				<th>Plot Summary</th><td id="plot">'+arr[i].plot+'</td>'+
					'			</tr>'+
					'		</table>'+
					'		<br>'+
					'		<div>'+
					'			<a href="'+arr[i].imdbRef+'"><img src="images/imdb.jpg" class="linkButton" /></a>'+
					'			<a href="'+arr[i].wikiRef+'"><img src="images/Wiki.png" class="linkButton" /></a>'+
					'		</div>'+
					
					'	</div>'+
					'	<div data-role="footer" data-position="fixed" data-tap-toggle="false">'+
					'	<!-- http://stackoverflow.com/questions/11827622/data-position-fixed-doesnt-work-using-jquery-mobile  -->'+
					'    <div data-role="navbar">'+
					'        <ul>'+
					'            <li><a href="#" data-rel="back" data-icon="arrow-l" ></a></li>'+
					'            <li><a href="home.html" rel="external" data-role="button" data-icon="home"></a></li>'+
					'            <li><a href="info.html" rel="external" data-icon="info"></a></li>'+
					'        </ul>'+
					'    </div>'+
					'	</div>'+
					'</div>');
					
	
	$('#_'+(i+1928)).html($out);
	
	// retrieve state of switch from local storage
	var yearStr = "sw"+(i+1928);
	var yearCode = localStorage.getItem(yearStr);
	
	// if it was turned on previously, add checked attribute to the switch
	if(yearCode == 1)
	{	
		$('.checkSwitch').prop('checked', true);
	}
	else 
	{
		$('.checkSwitch').prop('checked', false);
	}
	
	//when toggle is changed, run the toggle function from oscarToggleScripts.js
	var tswitch = '#'+arr[i].switchId;
	$(document).on('change', tswitch, function(){
		myToggleYear();
	});
}

// create page using array and the year supplied from local storage
var yearId = localStorage.yearId;
$(document).ready(jQPages(films, Number(yearId)));


